// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMMIFOwqRLiJt9I2XcKC_T7ClwL47UcCI',
    appId: '1:30313954522:android:8d537ba7d0abc9fd31f9e3',
    messagingSenderId: '30313954522',
    projectId: 'imagecap-c97f1',
    databaseURL: 'https://imagecap-c97f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'imagecap-c97f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRxN8pc05xWw-5a2eO7dvMLvfuZ2J_wpU',
    appId: '1:30313954522:ios:908f86a993bc64e131f9e3',
    messagingSenderId: '30313954522',
    projectId: 'imagecap-c97f1',
    databaseURL: 'https://imagecap-c97f1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'imagecap-c97f1.appspot.com',
    iosClientId: '30313954522-jmqjm2mddf9grgk5ppl7op0dd67pli4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.riveAnimation',
  );
}
